FROM --platform=linux/amd64 node:21 as builder
WORKDIR '/app'

COPY package.json ./
COPY package-lock.json ./

COPY . .
RUN npm install --silent

# FROM --platform=linux/amd64 nginx:1.25.3
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf
# COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 3000
CMD ["npm", "run", "start"]
# CMD ["", "index.js"]
# CMD ["nginx","-g","daemon off;"]

