FROM --platform=linux/amd64 node:21 as builder
WORKDIR '/app'

COPY package.json ./
COPY package-lock.json ./

COPY . ./
RUN npm install --silent
RUN npm run build

FROM --platform=linux/amd64 nginx:1.25.3
COPY --from=builder /app/build /usr/share/nginx/html
